version: "3"

services:
  vmessy:
    build:
      context: .
    volumes:
      - ./config:/etc/config
    network_mode: "host"
    depends_on:
      - xray

  xray:
    image: teddysun/xray:1.7.5
    volumes:
      - ./config:/etc/xray
    network_mode: "host"
